### ISSUE TITLE
Facilitate single-image execution

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/FEATS#24]
Currently, the scheduler image never does work, which is reasonable for multi-image execution, but it's also important to allow for single-image execution -- especially because that's the default `fpm` build.  Current single-image runs hang because there are no compute images to do the tasks.

**Comment by everythingfunctional** [comment]
I did implement a method for single image execution, and then promptly changed scheduling algorithms to one which works in single image anyways.
